[package]
name = "Kaiten"
version = "0.1.0"
edition = "2021"
license = "BSD-Z"
license-file = "LICENSE"
authors = ["Colleen <colleen@colleen05.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
